{
 "title": "Pulsar / Debezium Source",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(debezium_postgres_connector_metrics_TotalNumberOfEventsSeen[5m]))",
     "legendFormat": "{{ kubernetes_pod_name  }}"
    }
   ]
  },
  {
   "title": "Commited Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(debezium_postgres_connector_metrics_NumberOfCommittedTransactions[5m]))",
     "legendFormat": "{{ kubernetes_pod_name  }}"
    }
   ]
  },
  {
   "title": "Connected Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (debezium_postgres_connector_metrics_Connected)",
     "legendFormat": "{{ kubernetes_pod_name  }}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (debezium_postgres_connector_metrics_NumberOfCommittedTransactions)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Events Seen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (debezium_postgres_connector_metrics_TotalNumberOfEventsSeen)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {},
    {},
    {}
   ]
  }
 ]
}