pulsar-operator:
  operator:
    image: datastax/pulsar-operator:latest
    imagePullPolicy: Always

pulsarGrafanaDashboards:
  enabled: true

kube-prometheus-stack:
  enabled: true
  grafana:
    adminPassword: grafana1