#
#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kaap:
  operator:
    enabled: true
  cluster:
    create: true
    spec:
      global:
        name: pulsar
        image: datastax/lunastreaming-all:2.10_3.4
        restartOnConfigMapChange: true
        antiAffinity:
          host:
            enabled: false
        tls:
          enabled: true
          zookeeper:
            enabled: true
          bookkeeper:
            enabled: true
          autorecovery:
            enabled: true
          proxy:
            enabled: true
            enabledWithBroker: true
          broker:
            enabled: true
          certProvisioner:
            selfSigned:
              enabled: true
              zookeeper:
                generate: true
              broker:
                generate: true
              bookkeeper:
                generate: true
              autorecovery:
                generate: true
              proxy:
                generate: true
      zookeeper:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      bookkeeper:
        replicas: 3
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
      broker:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
        kafka:
          enabled: true
        autoscaler:
          enabled: true
          periodMs: 20000
          min: 2
          max: 10
          lowerCpuThreshold: 0.2
          higherCpuThreshold: 0.4
          scaleUpBy: 1
          scaleDownBy: 1
          stabilizationWindowMs: 120000
        config: {}
      proxy:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
        kafka:
          enabled: true
        config: {}
cert-manager:
  enabled: true
  installCRDs: true
