{
 "title": "Starlight RabbitMQ",
 "tags": [ "RabbitMQ" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pulsar_proxy_rabbitmq_active_connections"
    }
   ]
  },
  {
   "title": "New connection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_proxy_rabbitmq_new_connections[60s])"
    }
   ]
  },
  {
   "title": "In message total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_proxy_rabbitmq_in_messages_total[60s])"
    }
   ]
  },
  {
   "title": "Out messages total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_proxy_rabbitmq_in_messages_total[60s])"
    }
   ]
  },
  {
   "title": "In bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_proxy_rabbitmq_in_bytes[60s])"
    }
   ]
  },
  {
   "title": "Out bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pulsar_proxy_rabbitmq_out_bytes[60s])"
    }
   ]
  }
 ]
}