{
 "title": "Pulsar / Load Balancing",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "pulsar_lb_memory_usage{job=~\"broker.*\", kubernetes_pod_name=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bandwidth In Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Unload Broker Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_broker_count{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Unload Bundle Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_bundle_count{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bundles Split Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bundles_split_count{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "instance" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}