{
 "title": "Pulsar / Pulsar Heartbeat",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "End-to-End Topic Pubsub Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pulsar_pubsub_latency_ms", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Instances offline counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_k8s_bookkeeper_offline_counter"
    },
    {
     "expr": "pulsar_k8s_broker_offline_counter"
    },
    {
     "expr": "pulsar_k8s_zookeeper_offline_counter"
    },
    {
     "expr": "pulsar_k8s_proxy_offline_counter"
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pulsar_tenant_size  ", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Tenants",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(pulsar_tenant_size)" }
   ]
  },
  {
   "title": "Uptime hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_monitor_counter)/7200"
    }
   ]
  },
  {
   "title": "WebSockets Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pulsar_websocket_latency_ms", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "End-to-End Function Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pulsar_func_topic_latency_ms", "legendFormat": "{{ device }}" }
   ]
  }
 ]
}