#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Base ClusterServiceVersion template containing static information
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kaap.oss.datastax.com/v1alpha1",
          "kind": "PulsarCluster",
          "metadata": {
            "name": "pulsar"
          },
          "spec": {
            "global": {
              "name": "pulsar",
              "image": "apachepulsar/pulsar:3.0.0"
            }
          }
        }
      ]
    alm-examples-metadata: |-
      {
        "pulsar": {
          "description": "Example of a Pulsar cluster"
        }
      }
    capabilities: Auto Pilot
    categories: Big Data, Streaming & Messaging
    containerImage: docker.io/datastax/kaap:0.1.0
    createdAt: "2023-05-07T00:00:00Z"
    description: Kaap (Kubernetes Autoscaling for Apache Pulsar) manages the complete lifecycle
      of Apache Pulsar clusters.
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/project_layout: unknown
    repository: https://github.com/datastax/kaap.git
    support: Datastax
  name: kaap.v0.1.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Autorecovery
        name: autorecoveries.kaap.oss.datastax.com
        version: v1alpha1
        displayName: Autorecovery
        description: This custom resource is intended only for internal usage by the operator.
      - kind: Bastion
        name: bastions.kaap.oss.datastax.com
        version: v1alpha1
        displayName: Bastion
        description: This custom resource is intended only for internal usage by the operator.
      - kind: BookKeeper
        name: bookkeepers.kaap.oss.datastax.com
        version: v1alpha1
        displayName: BookKeeper
        description: This custom resource is intended only for internal usage by the operator.
      - kind: Broker
        name: brokers.kaap.oss.datastax.com
        version: v1alpha1
        displayName: Broker
        description: This custom resource is intended only for internal usage by the operator.
      - kind: FunctionsWorker
        name: functionsworkers.kaap.oss.datastax.com
        version: v1alpha1
        displayName: FunctionsWorker
        description: This custom resource is intended only for internal usage by the operator.
      - kind: Proxy
        name: proxies.kaap.oss.datastax.com
        version: v1alpha1
        displayName: Proxy
        description: This custom resource is intended only for internal usage by the operator.
      - kind: PulsarCluster
        name: pulsarclusters.kaap.oss.datastax.com
        version: v1alpha1
        displayName: Pulsar cluster
        description: The PulsarCluster CR defines a Pulsar cluster configuration and capabilities.
      - kind: ZooKeeper
        name: zookeepers.kaap.oss.datastax.com
        version: v1alpha1
        displayName: ZooKeeper
        description: This custom resource is intended only for internal usage by the operator.
  description: |-
    Kubernetes Autoscaling for Apache Pulsar (KAAP) simplifies running Apache Pulsar on Kubernetes by applying the familiar Operator pattern to Pulsar components, and horizonally scaling resources up or down based on CPU and memory workloads.
    
    ## Installation
    This operator can be installed from [OperatorHub.io](https://operatorhub.io/operator/kaap).
    After the operator is up, proceed deploying a Pulsar cluster using the the Custom Resource Definition below.
    
    ```sh
    kubectl create -f https://raw.githubusercontent.com/datastax/kaap/main/olm/examples/dev-cluster/cluster.yaml
    ```
    

  displayName: Kubernetes Autoscaling for Apache Pulsar
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAAArCAYAAADIWo5HAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA3XAAAN1wFCKJt4AAAScElEQVRo3u2aeXxc1XXHv+e+WTTaJS/IkrzbYEcGL6OZsbw0iklYDAST1AmhTRq6JKVZSElDGiihodBC0yQ4pdlaUtKwBSekhNAQVrnYkmZGg1fZeMPGtmTLshbLljSaee+e/qGRIhxhtkD+6f1nPnPXc39nP/fB/7fff6urqwsBMt5YTU1NAKC+vt43MicWi1UD5ndxtnk3LzpymWg0OgGgtrb2PADXda8AdO3atc6yxYunjwITjV5eWloaBBgcHKwFdEU0utBauxiwI3suXbRoRm6JhMPhKQDhcHhi7nf22WiSdxOAWCTyqZKhoQdOBgJXDLluc9Dv/6qKvGhUP61wH/DHgby81Z7neW4m80VxnKPxeHxdLBL5O5/qIypS7MHn48nkn4wAEKut/UK8peVfAS8WidzmWvsNEVntpNPPucFglV+kuLmlpeH3CsCDLe0TGx/9z+tann381vzCon5/MOgbGjgd9Dwr2aG0UdXfWuM4Pm9GzcKnjuzdNdPNDO1Ra39iVf9WHOcvcN3y5paWX9XFYl/F2g1NyeSGSDj8d47jWJ8xja61H1WRL+N598RbWj4xVuKXL15csWnz5vZ3FIBv/8/eYO/h+HV7Xoz/xbFX9p97urfHp577lvcL5IXIpAcpnVix82T38UBeKHT+4MDAbQKh5kTic0uj0RvU2osF7laRf8u47oqAz/cjY+0NTanUdoDly5cXZdLpr3Z2dd1y8ODB9DsCwJe//q/XHH/l4Fde2bmlpv9Unyhg8wrJ5JfghYogEKJm6mS8vh729qQZKCzHC+SDETx/COO5+Pp7Kew8wJKKYvIKizh+/ATHDh8km8kAkFdYpIFA3vH+vt5Dhf2n39cbDH7dwEKr+oQx5hYV+RSed62IPNecTN4OUBcOz7PGPCJwQ3My+Uw4HPYDE1Op1NG3DUB9fb1vyuzzbuo7cfxLJ9qPFBYWl9DlFOCUTeZ45Xtwg4VMznP41IUR7JG9fL/lAB0T5zBnYhG7T5xiYUUpW4/14jOCa4dVQaxlQbaD893jrF6zlu6uTnbt3MWxV/Zz6KUd9HV1Mi+2Mrtvc7LPzaQnAH1AkcK9AjUicqA5kfh4LBYrFGu/hMjfWLgpkUh8a9GiRaVBn++KeEvL/YD63urFw+Gwv6ik5DOCuf3w7p0FcxdcwEVXfZSfbN3PkbI55J/qJH9iBZ3Wz0enC3+1YgGr/znF0YlzuGRuBbPLCzjSN8ifL5nBTc/uYMmUMjYc7ARAjaGsKJ/13VO5Ao+F0WVULajlROcJejqOcnj3Dl7esdmv1p2QI6dYVTMici1wDNWHY5HIj8TaK4GAqN6RSCbvjobDl4kxUePz3QkogPOWrHksdlHQH3zO89y1c5csDaz59A2s/vBHmHv+Ir65vRPrD5INFPDHM0Ls6hnkU4un8ZGvrWPG4iihvDwunDWZfL+Pq+ZXMr20gGhVOY/ubGPxlFL6+vv50Ydj7Hv5IDullJLeNhbV1KDiYEKFlJ0zhco586iePY/KOfMAoevo4SwQyLn1YuBS4AIgqPCSqPZUVVXdKiKnQgUFd23cuHHUBvjeZMBSZT3vB6heNGPhElasuUamzzufUDBAKCicTGewvsAwFx0fLyQ38/Mb/pIv3PszLrjsD2k93sffLD+XeeUF1FSU4TOCVWVmaT63vu89bHzlBC27+5jrpOF0L0gRJ+2wlpoxyuoPBDlnxmwmTZ3BtPMWMK+2zv3F9/6lwfO8esB/RqAz14ocUfjbZDL5/Ij7fNMALIvFrvZc9/uOz9d91eduHqype2+RP5j3qjkh/6u32188nbmFDu2EeHl/B7dfuIDF5xRz7qSS3xAowpSiELUVJRw7leZblyziinWP0D5pDgiUFxW/prU2jsPE6umUVVSFPMuvfvHdu36K6ipEigVOKbzsM+aJntOnt7S2tp4e716+NyDuxWrtv3vWrlHVH3/+ngdnTZhSPWPsnBE3HnAMRTbNKTMMTLkO8cCGBNdPE8pr5lJdWsCsCUXjnjOzvJCVVYPc82gj3uxF6OlhKV103hwArL42jY7PR/iiy/Wx79xZLyJ/IMY8aVXXJRKJbSO6/pZC4WXh8GxRTQksU5FP3vKTn981YUp1/ZnzxsrU/OLfSGApGVqOD/CDrnyObG6iwufhmPGPFBFOdHZyrHwmPYPDLi+QHaRm9kwAPD07o352923zRORjQIV6XkZdd3ZdXV3lW84F6qLRiz1jXrSq+/0iFyYSiYfy8qcsHk8arf6GwKvrFo32u54yvbqSQEExzwRncn9zK5mcPz+zuZ6HyaT57DT4eCU4XpalZQaR4eMyZxGBU71d6W0bnrlmNLYR+TPHcb6sqkveEgDRcPgGq/qgwNc9az+0MZHYM+yfXztwSns59zh7GtNNGrEu6z6xmlsvjbKkxDC1JJ+iimq6+tPjru9NZ+ktruDa5h5+Ht/BDdWW6y9fNcr9rB3/XM91uffmz3aAjuqWQrsj8hnP87qi0WjtmwIgFon8kxjzMYy5sjmZvCOVSg2Mcsm6qdfSqX5XR/X0jjXvpSjdx+zyQgDOGerml7uPUmYHSW7ZzmDW5eTpAVzPI+t6NB7o4KEdR3h4+2FWn1dJV+V7aHOKmFhaOszh7PjcV1Ueuuvm9hNHXqkCRmLtXhF5xoXPDwwMtCQSiZazRbxjB2Rpbe1XrTH5/f39d7W2tnaPt+DptuzjCJePNxZyhJJAbl5qG/c/+hiXz5nExsF8Boonc3usmue6XDLi55K5FfQNZTl0cpDtHSeZVBCk8dAJdhzvo77E42sf+yAAQx70ZHQczmd58M6bj+9Obpxs4AueyCYDF6u1l4oxGyz83KhGnEDg/k2bNp16XQBqa2uXB40Z2pRIvHimrxzbnj+i1a5xm4Gq8cYL/UJhzrc817KFbzRs4dsX1XBMCvjBkxt478qV/HjrIf50yQxOprMcPZ0m5HN4en8HE/L8XDwlxKcvXgkMi31PRn/LA5w8cdz+8ObPHu06dmSEhi4L708mk1tisVixiNRbazs9z9vqU52P3783Ho/3nQ0Aqa+vdxoaGt5QyvZMR3oWnvOIQnhcEHxCgX94887uLja1bOaq8Dzqf/IiwWAAR4Q8n4NnlXMKgxw5OcCsPMsNF9Uxc1JZzuhB7xmXV2vZ9IuHDz31o+9MstaGfmOF7W3WmA5jzNPxeHxvLkfJa2hoSANSv2hRScOWLSfHU18BWBGJzMqqLhafL9Xc3HxwvEutWLGiLJPJlDrWlmLtqekLlw792e3rPo/wGSD0WymsgZKA4AijkdzGrTtpOtxB95Di+BwmFORTUz2Z8LTJlIVCozFFvwunXX3VxVuefvzAr++7J5Ae6K9SOIxqlYh8V1U/Avws0dJyXXjWrJKi4mJp2LKl72xSPK4ExGKxOaK6VmEeqiUKpUC5QAmqxTl/FADyxjjvbsfv33HByvcTueiqBVPPnV8uY/y8AHmOkO8D/+sU36zCoPdqY9px+OCx5x+698Cu+IbZnutOHmO5v6AiVq2tMSL/5cGPFT6YTCZbc8fKmwVgbJZX4jhOubU24FcNeI7zKtKDxhRmrV2hqnfmuk6IiKOqZcZxTp0zbVbHrIUR36wLlkyaOmd+QX5J2agE+GT4VxBEwKqiCq6C61n32CsHju7b3HyotanBa395z2zrZkftjKh+T405D9V64Kl4MnnJsiVLVokxbRbyLdwYb2n5ozd68bdVEInV1l6NyN0K9yk8bOAjwI3ABmAfEAMWAvj8/t5gKL8rv6j4dKiwJOsL5GUUq9mhtHUzGd+p7q6CdP+pYs9zK14lXcMK+6QMS90K4LuDQ0M3h4LBLwrcpK67JL55886amprC1tbW03V1ded7nhdNJBL3vqMARKPRmaL6FePzPdDX19fU2tqaiUUiDwEtrrUPplKpY7FYbDLWHhgJH4AioAuYAIzEFfkCO3R4fJHAkEJA4D9U5IOo5hufb77p7u7LFBevFvjH/IKC8xoaGrxobe2XRCQaTyb/cCxty5cvryGTYdOwKryh9qbqAcuXLy9yXXe+z+9/tKmpaXtnZ6cXiURmedaeGBgcfGDr1q0nAaZWVq4CagX+WozJAj2IbAXmi8iXUH1MYZlRXe0PhX7guu77BbYAfoVuz9rrHZG1Pr//vk2bN3e0t7e3VldVBazrTjvS1ra9rb29qaqyMjZtypT2I0ePHh+h7/Dhw52V5eWm7fjx9OslQW/pXaCysnKot7e3qampqW10A2MyJ0+e/FVra2tmNHuEVRY+2ZxMrree121V7xDVWoVHB9LpH8ZbWn5oRFovTqX2vPDCC50CT6iqgzFXiMhy4JDANZl0+sMj58STyW951i4dsZndvb1fscZcdiaN8R07Ot6MHXhTAKxfvz6zb9++oVcdGI+3j+kTH4QtfDOZTCYBFWgyxhxVCDnW3r5t27b+XBj72JiQ9iDG9Mfj8Z0KN/rgL5uSyWeBI2No9ESkZ0Rt9+3bN+Ra+2AkEqkZL0p+N1+GRtFeu3atscY0J5PJwyN9pwcHnxRrP6Qi9zSlUjtGF3nei+trany5IqhV2A+QSCQewpiK4SRIfxqJREbdn6O6KxKJvGfkfyqVOpSzLW+5uOvjd9jWr1/vAYNj+1pbW/tjkchU4KaxnAkMDGy2hYUhIKM+3zTP85pHuGeM2XbhvHkTnk2luoBRHQ+oPpMVWQWMGrlkMnns7QDwjr8N1tXWRoznPZpIJLrG9m/avftUKpU6lfPxJhgMNo66Jsf5ZX9p6bIzJawhlTpRYO22tyPy7zoAGVXJiLxwNvUR2NPY2Ng50tnY2HjI87z88RY0pFK7f5f0+d5pAIqKilobGhoGzjZHjdl+BhdVRF56relLI5FPAvV5BQV//kYTuN8bAA0NDadfb47rurt+q8DS37/rLEu+qFD5di//rn8f8FotlUplz+wbiSvGFQGRGQovvWMqUFdXF1LX/aiFeQa2NyeTD4ykxNmhoTWqOtsY062el4inUhtXrFhRlkmnPykipRhzfzwe35t7kFyrqmlxnO+PFCSWhsNL1Jj3qWqZwMuu6q+Akz6RD+M4HcaYFuu61wKD8WTyO2NC8IuxdiXG9KFaaGBvrn+NUTVWZINRvc6DB5PJ5MtLly6doZ63GqgWOOzB/ybHCZGdcbLBiaLaxHCJOYOItLW1Pb00HF7iWdsMRGTY1X1RRIpKysoe8xnTIsbEBPyi+tLUKVMC1pgXgQIxZgoi/9PW1tYfi0RuQ+R+RDyBhYhc54g86aiWYswTqKZV9Q7gCmBNVXX1f7e1tXXEIpEfCvyLQDcQFpiqquvb2ttfqK6s3I6IH9XrgWus6n9Mq6qqt6rPClTk0vrrBQ63tbdvfF0V8Iv8AzDfqq5KJJOXxhOJG2tqagJqzE+BHl8gEBbVdbl6wN6ioqLZwDxRTUydMWNNczL5jDVmFRBS1R/HE4nL4vF4RzQavRy4RVW/Fk8kLhPVrQDGdfeqSEXu+I8rfFbgTgDH2mCstnY1cK2I/FO8peUqgQdGPMeKFSvKAB+qHxCRHSpyoTGmX+E+EXkynkzWGfhFLtzc+4ZsgIpcDaRyoSwABQUFFwEzgW9v2rTplBpzZc6H7clms/sEkgrXHDp48PH6+vo8x9pfA10i8r1YJHILQO4zmKH8wcFv1NTUBFTkUiDduHnzYYVZuUs9mkgkfo3qDADPmP2I/CmA8fnW5eZ8KPcJyR53cPDcXBCQMY7z6UQi8RzWfgIIIXJnrs5yZW7+6wOQQ7QUGDpDJc4fQX1ZODwbkc/lQtO9qVQqm7X2AwpPApcODAxc0ZhK7RfHWQkcAL62cvHiSQoLBNoaWltPF+Xn3whUynDtwIrI/Nxx/5ljwvlARyKR6EJ1LpBpbGzsjEajaxQuzEWLe9WYuTnuPtzU1DSYe2E6H8Dv9++ui0QuAS4G1HXdfa9rBDdu3NgbjUQ6BSKxSGSdDqe0vwSyOcJu9YyZkQtFY2JtR7S29tbc8j7AA/ZEI5H7rbXbBHqAwIAxvT7IALNikchjCtVAP9CRU6X5qKbF59uU22uewO7cWC8QiNXWPo5qDcPWf1pTU9NgLBKZm0tJnx/zWJBBhGwmc7/AAob3qRj7vnE2FVCFjwFx4AJUnyjv6fmma+0DqD4vqr2ierXAI6g+NeB5XUZkl4hcIqqlKnJlIpHYakRekeFi5R5xnA/k3Nw/CGwGXnatXQW8qPBMLhTuRPUrOS4KsAeRx3KX+3uBJNCnw3nAU+T0WkX6Fb4rIs+OudDdQALoMsPn/C9jMs//b2e0/wN9e4NUfTzeDwAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec: null
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apachepulsar
  - pulsar
  - messaging
  - streaming
  maintainers:
  - email: streaming-eng@datastax.com
    name: Datastax Streaming Engineering
  maturity: alpha
  links:
    - name: Website
      url: https://docs.datastax.com/en/streaming/kaap-operator/latest/index.html
    - name: Documentation
      url: https://docs.datastax.com/en/streaming/kaap-operator/latest/index.html
    - name: Support
      url: https://docs.datastax.com/en/streaming/kaap-operator/latest/index.html
    - name: GitHub
      url: https://github.com/datastax/kaap
  provider:
    name: Datastax
    url: https://www.datastax.com
  replaces:
  version: 0.1.0
  minKubeVersion: 1.16.0

