#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Base ClusterServiceVersion template containing static information
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kaap.oss.datastax.com/v1alpha1",
          "kind": "PulsarCluster",
          "metadata": {
            "name": "pulsar"
          },
          "spec": {
            "global": {
              "name": "pulsar",
              "image": "apachepulsar/pulsar:3.0.0"
            }
          }
        }
      ]
    alm-examples-metadata: |-
      {
        "pulsar": {
          "description": "Example of a Pulsar cluster"
        }
      }
    capabilities: Real-time messaging, event streaming, and pub/sub system.
    categories: Big Data, Streaming, Messaging
    containerImage: docker.io/datastax/kaap:0.1.0
    createdAt: "2023-05-07T00:00:00Z"
    description: Kaap (Kubernetes Autoscaling for Apache Pulsar) manages the complete lifecycle
      of Apache Pulsar clusters.
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/project_layout: unknown
    repository: https://github.com/datastax/kaap.git
    support: Datastax
  name: kaap.v0.1.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: PulsarCluster
      name: kaap.oss.datastax.com/v1alpha1
      version: v1alpha1
      displayName: Pulsar Cluster
      description: The PulsarCluster CR defines a Pulsar cluster
  description: |-
    Kaap (Kubernetes Autoscaling for Apache Pulsar) manages the complete lifecycle of Apache Pulsar clusters.
    TODO: add quick readme
  displayName: Kubernetes Autoscaling for Apache Pulsar
  icon:
  - base64data: "TODO"
    mediatype: image/svg+xml
  install:
    spec: null
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apachepulsar
  - pulsar
  - messaging
  - streaming
  maintainers:
  - email: streaming-eng@datastax.com
    name: Datastax Streaming Engineering
  maturity: alpha
  links:
    - name: Website
      url: TODO
    - name: Documentation
      url: TODO
    - name: Support
      url: TODO
    - name: GitHub
      url: https://github.com/datastax/kaap
  provider:
    name: Datastax
    url: <LINK TO DOC>
  replaces:
  version: 0.1.0
  minKubeVersion: 1.16.0

