pulsar-operator:
  operator:
    image: datastax/pulsar-operator:latest
    imagePullPolicy: Always

keycloak:
  enabled: true
  auth:
    adminUser: "admin"
    adminPassword: "adminpassword"
  postgresql:
    postgresqlPassword: "xinf-2-doHTG._sMJi3*kZgQAabuet"
