{
 "title": "Pulsar / BookKeeper Compaction",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bookie Reclaim Compaction Space (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookie_RECLAIMED_COMPACTION_SPACE_BYTES[5m]) ",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bookie Reclaim Deletion Space  (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookie_RECLAIMED_DELETION_SPACE_BYTES[5m]) ",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Major Compaction (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookie_MAJOR_COMPACTION_COUNT[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Major Compaction (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookie_MAJOR_COMPACTION_COUNT[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Active Entry Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookie_ACTIVE_ENTRY_LOG_COUNT", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  },
  {
   "title": "Active Entry Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bookie_ACTIVE_ENTRY_LOG_COUNT", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  },
  {
   "title": "Active Ledger Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bookie_ACTIVE_LEDGER_COUNT", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  },
  {
   "title": "Deleted Ledger Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bookie_DELETED_LEDGER_COUNT", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  }
 ]
}