{
 "title": "Pulsar / JVM",
 "description": "JVM Related Metrics",
 "tags": [ "pulsar" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "jvm_memory_bytes_used{cluster=~\".+\"}"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "jvm_memory_bytes_used{job=~\".+\"}"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "jvm_memory_bytes_used{job=~\"$job\", kubernetes_pod_name=~\".+\"}"
   }
  ]
 },
 "panels": [
  { "title": "$job - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{kubernetes_pod_name=~\"$instance\"}[60s]) * 100\n\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{kubernetes_pod_name=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$instance\"}[60s]))",
     "legendFormat": "Pause"
    }
   ]
  }
 ]
}