{
 "title": "Pulsar / Offload",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Offload Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_offloaded_size)",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Offload By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  pulsar_storage_offloaded_size\n)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Byte Rate Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(rate(pulsar_storage_offloaded_size[5m]))/300 > 0",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Offload  Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(pulsar_storage_offloaded_size[5m]))/300)"
    }
   ]
  }
 ]
}