{
 "title": "Pulsar / Starlight for Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "In bytes rate by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_BYTES_IN[5m])) by (tenant)"
    }
   ]
  },
  {
   "title": "Out bytes rate by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_BYTES_OUT[5m])) by (tenant)"
    }
   ]
  },
  {
   "title": "In message rate by tenant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_MESSAGE_IN[5m])) by (tenant)"
    }
   ]
  },
  {
   "title": "Out message rate by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kop_server_MESSAGE_OUT[5m])) by (tenant)"
    }
   ]
  },
  {
   "title": "Failed produce message conversions time nanos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.5\"}[1m])",
     "legendFormat": "50%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.75\"}[1m])",
     "legendFormat": "75%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.95\"}[1m])",
     "legendFormat": "95%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.99\"}[1m])",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Produce message conversions time nanos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.5\"}[1m])",
     "legendFormat": "50%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.75\"}[1m])",
     "legendFormat": "75%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.95\"}[1m])",
     "legendFormat": "95%"
    },
    {
     "expr": "rate(kop_server_PRODUCE_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.99\"}[1m])",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Failed consume message conversions time nanos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.5\"}[1m])",
     "legendFormat": "50%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.75\"}[1m])",
     "legendFormat": "75%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.95\"}[1m])",
     "legendFormat": "95%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"false\", quantile=\"0.99\"}[1m])",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Consume message conversions time nanos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.5\"}[1m])",
     "legendFormat": "50%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.75\"}[1m])",
     "legendFormat": "75%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.95\"}[1m])",
     "legendFormat": "95%"
    },
    {
     "expr": "rate(kop_server_CONSUME_MESSAGE_CONVERSIONS_TIME_NANOS{success=\"true\", quantile=\"0.99\"}[1m])",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Failed request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kop_server_REQUEST_LATENCY_count{success=\"false\"}) by (tenant)"
    }
   ]
  },
  {
   "title": "Successful request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(kop_server_REQUEST_LATENCY_count{success=\"true\"}) by (tenant)"
    }
   ]
  },
  {
   "title": "Active channels by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(kop_server_ACTIVE_CHANNEL_COUNT) by (tenant)"
    }
   ]
  },
  {
   "title": "Request queue size by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(kop_server_REQUEST_QUEUE_SIZE) by (tenant)"
    }
   ]
  },
  {
   "title": "Message publish latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(kop_server_MESSAGE_PUBLISH{quantile=\"0.5\"})",
     "legendFormat": "50%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_PUBLISH{quantile=\"0.75\"})",
     "legendFormat": "75%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_PUBLISH{quantile=\"0.95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_PUBLISH{quantile=\"0.99\"})",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Message consume latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(kop_server_MESSAGE_READ{quantile=\"0.5\"})",
     "legendFormat": "50%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_READ{quantile=\"0.75\"})",
     "legendFormat": "75%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_READ{quantile=\"0.95\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "sum(kop_server_MESSAGE_READ{quantile=\"0.99\"})",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Request queue size by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(kop_server_REQUEST_QUEUE_SIZE) by (tenant)"
    }
   ]
  },
  {
   "title": "Active channel count by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(kop_server_ACTIVE_CHANNEL_COUNT) by (tenant)"
    }
   ]
  },
  {
   "title": "Kop Queue latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(kop_server_KOP_EVENT_LATENCY[1m])"
    }
   ]
  },
  {
   "title": "KOP event queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "kop_server_KOP_EVENT_QUEUE_SIZE"
    }
   ]
  }
 ]
}