{
 "title": "Pulsar / Sockets by Component",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Producers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{job=~\"broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_consumers_count{job=~\"broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Proxy Sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_sockets{container=~\".*proxy\",container!~\"kube-proxy.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Broker Sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_sockets{container=~\".*broker\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bookkeeper Sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_sockets{container=~\".*bookkeeper.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_sockets{container=~\".*zookeeper.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}