#
#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.operator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    {{- include "kaap.labels" . | nindent 4 }}
  name: {{ include "kaap.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "kaap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
{{- if .Values.operator.config.restartOnChange }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end }}
      labels:
        {{- include "kaap.selectorLabels" . | nindent 8 }}
      namespace: {{ .Release.Namespace }}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "kaap.name" . }}
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          {{- if .Values.operator.resources }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- end }}          
          livenessProbe:
            failureThreshold: {{ .Values.operator.livenessProbe.failureThreshold }}
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.operator.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.operator.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.operator.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.operator.livenessProbe.timeoutSeconds }}
          name: kaap
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: {{ .Values.operator.readinessProbe.failureThreshold }}
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.operator.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.operator.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.operator.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.operator.readinessProbe.timeoutSeconds }}
      serviceAccountName: {{ include "kaap.serviceAccountName" . }}
{{- end }}
